title: My GitHub Page
description: My personal website
baseurl: "" # GitHub Pages doesn't require a baseurl for personal repos
url: "https://hnchenhn.github.io/" # 替换为你的 GitHub 用户名

theme: "jekyll-theme-cayman"  # 或者其他你使用的主题


nav:
  - Home: index.md
  - Page 1: my_interests.md
  - Page 2: my_profession.md