title: My GitHub Page
description: My personal website
baseurl: "" # GitHub Pages doesn't require a baseurl for personal repos
url: "https://hnchenhn.github.io/" # 替换为你的 GitHub 用户名

theme_config:
  sidebar:
    - title: "首页"
      url: "/home"
    - title: "interests"
      url: "/my_interests"
    - title: "Profession"
      url: "/my_profession"